### ISSUE TITLE
uninitialized constant Paperform::Submission::Curl

### ISSUE THREAD

**Issue by fmoudoute** [nekapoor/paperform-ruby#2]
I get the following when trying the very straightfoward commend from the description page :

Traceback (most recent call last):
      1: from (irb):9
      NameError (uninitialized constant Paperform::Submission::Curl)

Am i not doing something right ?
    require 'paperform'

    submission = Paperform::Submission.new(ENV['paper_form_secret'])

    submission.list('xxxxx')

**Comment by williamkennedy** [comment]
This should now be resolved. 

```
client = Paperform::Client.new(ENV['paper_form_secret'])
response = client.submissions(form: 'xxx', before_date: '2021-03-01', after_date: '2021-01-01')
```
